on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to build Nemoh programs
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Nemoh programs
      id: build_nemoh
      run: make docker_build docker_demo
